### PR TITLE
Plus Icon Visible

### PR DESCRIPTION
**Pull request by mdznr**
Allowing the plus icon to be shown.
Also reworked/improved the API for plus icon visibility.
Some improvements were made such that setHighlighted: does not need to fully complete every time the user moves their finger.

### CODE REVIEW

**Comment by yhpark** [comment]
Sorry for late response.. I'm really appreciate for your help!
Before merging it would be great if you could change indents with spaces instead of tab characters, also please squash some supplementary commits if possible.

**Comment by mdznr** [comment]
I tried squashing some commits. I believe all spacing is using spaces and not tabs.

**Comment by yhpark** [comment]
There were several lines with tab but I'll take it from here.
Again, thanks.

**Comment by mdznr** [comment]
I just use tabs for indentation and spaces for vertical alignment on the same indentation level. This way users can set their own preference for how wide tabs are. I tried running a script to convert tabs to spaces, but I guess it didn't fully work. Thanks, though!

**Pull request merged**
